# Generated by Django 3.2.10 on 2022-01-21 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stripesessiondetails',
            name='job',
        ),
    ]
