# Generated by Django 3.2.10 on 2022-01-10 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='sponsored',
        ),
        migrations.RemoveField(
            model_name='job',
            name='sticky_day',
        ),
        migrations.RemoveField(
            model_name='job',
            name='sticky_month',
        ),
        migrations.RemoveField(
            model_name='job',
            name='sticky_week',
        ),
    ]
