# Generated by Django 3.2.10 on 2021-12-30 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='Employment_type',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='job',
            name='Primary_Skills',
            field=models.CharField(max_length=15),
        ),
    ]
