# Generated by Django 3.2.10 on 2021-12-30 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211230_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillist',
            name='send_time',
            field=models.CharField(max_length=10),
        ),
    ]
