# Generated by Django 3.2.10 on 2022-01-11 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_job_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo/'),
        ),
    ]
