# Generated by Django 3.2.10 on 2022-01-03 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_job_remote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='Primary_Skills',
            field=models.CharField(max_length=50),
        ),
    ]
