# Generated by Django 3.2.10 on 2022-01-07 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_job_primary_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsoredJobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_until', models.DateTimeField()),
                ('stripe_payment_intent_id', models.CharField(max_length=150)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsored_post', to='api.job')),
            ],
        ),
    ]
