# Generated by Django 3.2.10 on 2022-01-20 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20220118_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stripesessiondetails',
            name='job',
        ),
    ]
