# Generated by Django 3.2.10 on 2022-01-08 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_job_sponsored'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='email',
        ),
    ]
