# Generated by Django 3.2.10 on 2022-01-08 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20220108_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='job_id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='api.job'),
            preserve_default=False,
        ),
    ]
