# Generated by Django 3.2.10 on 2022-01-08 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_feedback_job_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='message',
            new_name='feedback',
        ),
    ]
