# Generated by Django 3.2.10 on 2022-01-08 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_message_feedback_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='feedback',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.AddField(
            model_name='feedbackbox',
            name='Job_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.job'),
        ),
    ]
