# Generated by Django 3.2.10 on 2022-01-08 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20220108_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='feedback',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='FeedbackBox',
        ),
    ]
