# Generated by Django 3.2.10 on 2022-01-08 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20220108_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='feedback',
        ),
    ]
