# Generated by Django 3.2.10 on 2022-01-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_job_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='feedback',
            field=models.TextField(default=''),
        ),
    ]
