# Generated by Django 3.2.10 on 2022-01-08 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_job_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='remote',
        ),
    ]
