# Generated by Django 3.2.10 on 2022-01-08 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_job_remote'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetail',
            name='job',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='company_details', to='api.job'),
        ),
    ]
