# Generated by Django 3.2.10 on 2022-01-08 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_companydetail_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsoredjobpost',
            name='job',
        ),
    ]
