# Generated by Django 3.2.10 on 2022-01-08 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_sponsoredjobpost_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companydetail',
            name='job',
        ),
        migrations.AddField(
            model_name='sponsoredjobpost',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsored_post', to='api.job'),
            preserve_default=False,
        ),
    ]
