# Generated by Django 3.2.10 on 2022-01-08 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_companydetail_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetail',
            name='job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Companydetails', to='api.job'),
        ),
    ]
